import { React, useState, useEffect } from 'react';
import { useLocation, useParams } from 'react-router-dom';
import { nanoid } from 'nanoid';

import { ref, set, get, child } from "firebase/database";
import { Studentdb } from '../firebaseStudent';

import './main.css';
import NammaCompilerHeader from './NammaCompilerHeader/nammaCompilerHeader';
import NammaCompilerEnterTitle from './NammaCompilerEnterTitle/nammaCompilerEnterTitle';
import NammaCompilerMenuBar from './NammaCompilerMenuBar/nammaCompilerMenuBar';
import NammaCompilerEditor from './NammaCompilerEditor/nammaCompilerEditor';
import NammaCompilerInput from './NammaCompilerEditor/nammaCompilerInput';
import NammaCompilerOutput from './NammaCompilerEditor/nammaCompilerOutput';
import NammaCompilerAd from './NammaCompilerEditor/nammaCompilerAd';

const NammaCompilerMain = () => {

    const [isDark, setIsDark] = useState(false);
    const [editorCode, setEditorCode] = useState(`#include <iostream>

int main(){
  std::cout << "Still under Construction, users may face performance issues" << std::endl;
  std::cout << "Welcome to Namma Compiler! Made by SJCIT CSE CodeArena Club Students" << std::endl;
  return 0;
}`);

    const [lang, setLang] = useState('cpp');

    const [stdin, setStdin] = useState('');

    const [output, setOutput] = useState("");
    const [compileTimeError, setcompileTimeError] = useState("");

    const [langVersion, setLangVersion] = useState('C++ (GCC 14.1.0)');

    const [viewMode, setViewMode] = useState(false);

    const location = useLocation();
    const { uniqueCode } = useParams();

    const testCode = nanoid(21);
    // Section when the nammaCompiler is opened in the View mode, which will be generated by the `save` button.
    useEffect(() => {


        const isViewRoute = location.pathname.includes('/nammaCompiler/view');
        setViewMode(isViewRoute);
        console.log("The unique Code is: ", uniqueCode);
        console.log(location.pathname.split('/view/')[1]);
        const ref_code_in_db = location.pathname.split('/view/')[1];
        console.log("The ref code in db is: ", ref_code_in_db);
        console.log("The Nanoid Unique code is: ", testCode);

        const readData = async () => {
            try {
                const snapshot = await get(ref(Studentdb, ref_code_in_db));
                if (snapshot.exists()) {
                    console.log("The data is: ", snapshot.val().code);
                    const realCode = snapshot.val().code.join("");
                    console.log("The real code etched is: ", realCode);
                    setEditorCode(realCode);
                } else {
                    console.log("No data found");
                }
            } catch (error) {
                console.log("Read Failed: ", error);
            }
        }

        if (isViewRoute) {
            readData();
        } else {
            console.log("Not in view mode");
            //writeData();
        }


    }, [location.pathname]);


    return (
        <>
            <div className={`nammaCompiler ${isDark ? 'dark-theme' : 'light-theme'} `}>
                <NammaCompilerHeader isDark={isDark} setIsDark={setIsDark} shareCode={editorCode} editorCode={editorCode} testCode={testCode} />
            </div>
            <div className={`nammaCompiler2 ${isDark ? 'dark-theme' : 'light-theme'} `} >
                <NammaCompilerEnterTitle isDark={isDark} />
            </div >
            <div className={`nammaCompiler3 ${isDark ? 'dark-theme' : 'light-theme'} `} >
                <NammaCompilerMenuBar langVersion={langVersion} setLangVersion={setLangVersion} isDark={isDark} code={editorCode} setOutput={setOutput} stdin={stdin} setCode={setEditorCode} setLang={setLang} setCompilerError={setcompileTimeError} lang={lang} />
            </div>
            <div className={`nammaCompiler4 ${isDark ? 'dark-theme' : 'light-theme'} `} >
                <div className={`nammaCompiler4EditorMainDiv ${isDark ? 'dark-theme' : 'light-theme'} `}>
                    <NammaCompilerEditor isDark={isDark} setCode={setEditorCode} code={editorCode} lang={lang} viewMode={viewMode} />
                </div>
                <div className={`nammaCompiler4EditorSideMain ${isDark ? 'dark-theme' : 'light-theme'} `}>
                    <div className={`nammaCompiler4EditorInput ${isDark ? 'dark-theme' : 'light-theme'} `}>
                        <NammaCompilerInput isDark={isDark} setStdin={setStdin} />
                    </div>
                    <div className={`nammaCompiler4EditorOutput ${isDark ? 'dark-theme' : 'light-theme'} `} style={{ height: '60%' }}>
                        <NammaCompilerOutput isDark={isDark} outputText={output} compileTimeError={compileTimeError} />
                    </div>
                    {/* <div className={`nammaCompiler4EditorAd ${ isDark ? 'dark-theme' : 'light-theme' } `} style={{ position: 'relative' }}>
                        <NammaCompilerAd isDark={isDark} />
                    </div> */}
                </div>
            </div>
        </>
    );
};

export default NammaCompilerMain;
